name: Release notes
description: Build release notes from a CHANGELOG
inputs:
  file:
    description: Location of CHANGELOG file, default is ./CHANGELOG.md
    require: true
    default: "./CHANGELOG.md"
  version:
    description: |
      Version to pull CHANGELOG section for. Empty means "latest", and is the
      default.
    required: true
    default: ""
  version-header-regex:
    description: |
      Regular expression for marking version sections.

      This must capture the version itself as the first group. The default is a
      level-2 markdown header that contains a conventional version as a link.

      ^## [(v0.0.0-suffix)]

    required: true
    default: '^## \[(v?[0-9.]+[^]\s]*)]'
outputs:
  path:
    description: |
      The temporary file path where the release notes were written
    value: ${{ steps.run.outputs.path }}
runs:
  using: composite
  steps:
    - id: run
      shell: bash
      env:
        FILE: ${{ inputs.file }}
        VERSION: ${{ inputs.version }}
        VERSION_HEADER_REGEX: ${{ inputs.version-header-regex }}
      run: |
        path=$(mktemp)
        echo "path=$path" >>"$GITHUB_OUTPUT"

        while read -r; do
          if [[ "$REPLY" =~ $VERSION_HEADER_REGEX ]]; then
            if [[ -z "$VERSION" ]]; then
              VERSION=${BASH_REMATCH[1]}
            fi

            case "${BASH_REMATCH[1]}" in
              "v$VERSION" | "$VERSION")
                output=1
                ;;
              *)
                output=0
                ;;
            esac
          fi

          if ((output)); then
            echo "$REPLY"
          fi
        done <"$FILE" | tee "$path"
