name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: release-notes
        uses: ./
        with:
          file: ./files/CHANGELOG.md

      - run: |
          actual=${{ steps.release-notes.outputs.path }}
          expected=$(mktemp)

          cat >"$expected" <<'EOM'
          ## [v2.2.1.0](https://github.com/freckle/platform/compare/v2.2.0.0...v2.2.1.0)

          - Support a single `.platform.yaml`

            The following,

            ```yaml
            # $app/.platform/$resource-a.yaml
            inputs: a
            environments: b
            uses: x
            with: y

            # $app/.platform/$resource-b.yaml
            inputs: a
            environments: b
            uses: x
            with: y
            ```

            can now be simplified to,

            ```yaml
            # $app/.platform.yaml
            inputs: a
            environments: b
            resources:
              - name: $resource-a
                uses: x
                with: y
              - name: $resource-b
                uses: x
                with: y
            ```

            **NOTE**: you are encouraged to move to this style, support for separate
            resource files will be deprecated and removed in a future version.

          - Support multiple arguments to `query`

            ```
            platform query x y

            # Behaves the same as
            platform query x
            platform query y
            ```

          EOM

          diff "$expected" "$actual"

      # - id: explicit
      #   uses: ./
      #   with:
      #     file: ./files/CHANGELOG.md
      #     version: 2.2.0.0

      # - id: explicit-v
      #   uses: ./
      #   with:
      #     file: ./files/CHANGELOG.md
      #     version: v2.2.0.0

      # - id: not-found
      #   uses: ./
      #   with:
      #     file: ./files/CHANGELOG.md
      #     version: v42.42.42
