name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: release-notes
        name: "Release notes for latest version"
        uses: ./
        with:
          file: ./test/CHANGELOG.md
      - run: |
          diff test/latest.md "${{ steps.release-notes.outputs.path }}"

      - id: release-notes-2.2
        name: "Release notes for an explicit version"
        uses: ./
        with:
          file: ./test/CHANGELOG.md
          version: 2.2.0.0
      - run: |
          diff test/v2.2.0.0.md "${{ steps.release-notes-2.2.outputs.path }}"

      - id: release-notes-v2.2
        name: "Release notes for an explicit version (with v-prefix)"
        uses: ./
        with:
          file: ./test/CHANGELOG.md
          version: v2.2.0.0
      - run: |
          diff test/v2.2.0.0.md "${{ steps.release-notes-v2.2.outputs.path }}"

      - id: release-notes-not-found
        name: "Release notes for non-existent version"
        uses: ./
        with:
          file: ./test/CHANGELOG.md
          version: v42.42.42
      - run: |
          if [[ -s "${{ steps.release-notes-not-found.outputs.path }}" ]]; then
            echo "release-notes were incorrectly found for v42.42.42" >&2
            exit 1
          fi
